apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: sample-secret
spec:
  encryptedData:
    password: AgDGyhv7MujqS9CQJhrDP3/VBw8jNKl9hzcBnqBAmSAUTR3VqDv/7r/ycyQQs6LPh9NZ6VwYjgrP9EZKKvXcPwrE6Uyoy>
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: sample-secret
